name: gabe
favicon: null
layout_spectrum: 0.40956703945994377
typography_spectrum: 0.9806219446472824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bb2222'
    - '#787878'
    - '#bcbcc4'
    - '#282828'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.49591617309488356
  rhythmicContrast: 0.75
purpose: []
