name: gabe
favicon: null
layout_spectrum: 0.35464
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c8c8cf'
    - '#7f7f7f'
    - '#2a292a'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
