analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c8c8cf'
    - '#7f7f7f'
    - '#2a292a'
  brandStrength: 1
  lightness: 0.4375
  rhythmicContrast: 0.5
  saturation: 0.9375
cta: {}
layout_spectrum: 0.78752
name: gabe
opengraph: {}
purpose: []
typography_spectrum: 0.736486
